"""Unofficial Monarch Money API client."""

from monarch_api.functions.accounts import (
    create_manual_account,
    delete_account,
    get_account,
    get_account_history,
    get_historical_balances,
    get_net_worth_breakdown,
    get_net_worth_performance,
    list_accounts,
    update_account,
)
from monarch_api.functions.auth import create_session, load_session, save_session
from monarch_api.functions.categories import (
    create_category,
    create_category_group,
    delete_category_group,
    get_category,
    get_category_catalog,
    get_category_group,
    list_categories,
    list_category_groups,
    reactivate_category,
    remove_category,
    reorder_category,
    reorder_category_group,
    update_category,
    update_category_group,
)
from monarch_api.functions.common import (
    MfaRequiredError,
    MonarchAuthError,
    MonarchError,
    MonarchGraphQLError,
    build_auth_headers,
    graphql_request,
    rest_request,
)
from monarch_api.functions.merchants import (
    delete_merchant,
    get_merchant,
    list_merchants,
    update_merchant,
)
from monarch_api.functions.tags import (
    create_tag,
    delete_tag,
    get_tag,
    list_tags,
    reorder_tag,
    update_tag,
)
from monarch_api.types.accounts import (
    Account,
    AccountBalance,
    AccountFilter,
    AccountHistoryPoint,
    AccountType,
    Institution,
    NetWorthBreakdownPoint,
    NetWorthSnapshot,
)
from monarch_api.types.auth import AuthSession
from monarch_api.types.categories import (
    Category,
    CategoryCatalog,
    CategoryFilter,
    CategoryGroup,
    CategoryGroupReference,
    CategoryType,
)
from monarch_api.types.common import User
from monarch_api.types.merchants import Merchant, MerchantSort
from monarch_api.types.tags import Tag

__all__ = [
    "Account",
    "AccountBalance",
    "AccountFilter",
    "AccountHistoryPoint",
    "AccountType",
    "AuthSession",
    "Category",
    "CategoryCatalog",
    "CategoryFilter",
    "CategoryGroup",
    "CategoryGroupReference",
    "CategoryType",
    "Institution",
    "NetWorthBreakdownPoint",
    "MfaRequiredError",
    "Merchant",
    "MerchantSort",
    "MonarchAuthError",
    "MonarchError",
    "MonarchGraphQLError",
    "NetWorthSnapshot",
    "Tag",
    "User",
    "build_auth_headers",
    "create_category",
    "create_category_group",
    "create_manual_account",
    "create_session",
    "create_tag",
    "delete_account",
    "delete_category_group",
    "delete_merchant",
    "delete_tag",
    "get_account",
    "get_account_history",
    "get_category",
    "get_category_catalog",
    "get_category_group",
    "get_historical_balances",
    "get_merchant",
    "get_net_worth_breakdown",
    "get_net_worth_performance",
    "get_tag",
    "graphql_request",
    "list_accounts",
    "list_categories",
    "list_category_groups",
    "list_merchants",
    "list_tags",
    "load_session",
    "reactivate_category",
    "remove_category",
    "reorder_category",
    "reorder_category_group",
    "reorder_tag",
    "rest_request",
    "save_session",
    "update_account",
    "update_category",
    "update_category_group",
    "update_merchant",
    "update_tag",
]
